
class Autogenerated {
  bool? success;
  String? message;
  int? totalUsers;
  int? offset;
  int? limit;
  List<Users>? users;

  Autogenerated(
      {this.success,
        this.message,
        this.totalUsers,
        this.offset,
        this.limit,
        this.users});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    totalUsers = json['total_users'];
    offset = json['offset'];
    limit = json['limit'];
    if (json['users'] != null) {
      users = <Users>[];
      json['users'].forEach((v) {
        users!.add(new Users.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['message'] = this.message;
    data['total_users'] = this.totalUsers;
    data['offset'] = this.offset;
    data['limit'] = this.limit;
    if (this.users != null) {
      data['users'] = this.users!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Users {
  int? id;
  String? gender;
  String? dateOfBirth;
  String? job;
  String? city;
  String? zipcode;
  double? latitude;
  String? profilePicture;
  String? firstName;
  String? lastName;
  String? email;
  String? phone;
  String? street;
  String? state;
  String? country;
  double? longitude;

  Users(
      {this.id,
        this.gender,
        this.dateOfBirth,
        this.job,
        this.city,
        this.zipcode,
        this.latitude,
        this.profilePicture,
        this.firstName,
        this.lastName,
        this.email,
        this.phone,
        this.street,
        this.state,
        this.country,
        this.longitude});

  Users.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    gender = json['gender'];
    dateOfBirth = json['date_of_birth'];
    job = json['job'];
    city = json['city'];
    zipcode = json['zipcode'];
    latitude = json['latitude'];
    profilePicture = json['profile_picture'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    phone = json['phone'];
    street = json['street'];
    state = json['state'];
    country = json['country'];
    longitude = json['longitude'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['gender'] = this.gender;
    data['date_of_birth'] = this.dateOfBirth;
    data['job'] = this.job;
    data['city'] = this.city;
    data['zipcode'] = this.zipcode;
    data['latitude'] = this.latitude;
    data['profile_picture'] = this.profilePicture;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['street'] = this.street;
    data['state'] = this.state;
    data['country'] = this.country;
    data['longitude'] = this.longitude;
    return data;
  }
}
